allow_duplicate_hostnames: false
allow_duplicate_ips: false
allow_duplicate_macs: false
allow_dynamic_settings: false
anamon_enabled: false
authn_pam_service: "login"
auth_token_expiration: 3600
autoinstall_snippets_dir: /var/lib/cobbler/snippets
autoinstall_templates_dir: /var/lib/cobbler/templates
boot_loader_conf_template_dir: "/etc/cobbler/boot_loader_conf"
build_reporting_enabled: false
build_reporting_sender: ""
build_reporting_email: [ 'root@localhost' ]
build_reporting_smtp_server: "localhost"
build_reporting_subject: ""
build_reporting_ignorelist: []
cache_enabled: true
cheetah_import_whitelist:
 - "random"
 - "re"
 - "time"
 - "netaddr"
createrepo_flags: "-c cache -s sha"
default_autoinstall: /var/lib/cobbler/templates/default.ks
default_name_servers: []
default_name_servers_search: []
default_ownership:
 - "admin"
default_password_crypted: "$1$mF86/UHC$WvcIcX2t6crBz2onWxyac."
default_template_type: "cheetah"
default_virt_bridge: xenbr0
default_virt_file_size: 5
default_virt_ram: 512
default_virt_type: xenpv
enable_gpxe: false
enable_menu: true
http_port: 80
kernel_options: {}
ldap_server: "ldap.example.com"
ldap_base_dn: "DC=example,DC=com"
ldap_port: 389
ldap_tls: true
ldap_anonymous_bind: true
ldap_search_bind_dn: ''
ldap_search_passwd: ''
ldap_search_prefix: 'uid='
ldap_tls_cacertfile: ''
ldap_tls_keyfile: ''
ldap_tls_certfile: ''
mgmt_classes: []
mgmt_parameters:
 from_cobbler: true
puppet_auto_setup: false
sign_puppet_certs_automatically: false
puppetca_path: "/usr/bin/puppet"
remove_old_puppet_certs_automatically: false
puppet_parameterized_classes: true
manage_dhcp: true
manage_dns: true
bind_chroot_path: ""
bind_master: 127.0.0.1
manage_tftpd: true
tftpboot_location: "/var/lib/tftpboot"
manage_rsync: true
manage_forward_zones: []
manage_reverse_zones: []
next_server: 192.168.4.3
power_management_default_type: 'ipmilan'
pxe_just_once: true
nopxe_with_triggers: true
redhat_management_server: "xmlrpc.rhn.redhat.com"
redhat_management_permissive: false
redhat_management_key: ""
register_new_installs: false
reposync_flags: "-n --delete"
reposync_rsync_flags: "-rltDv --copy-unsafe-links"
restart_dns: true
restart_dhcp: true
run_install_triggers: true
scm_track_enabled: false
scm_track_mode: "git"
scm_track_author: "cobbler <cobbler@localhost>"
scm_push_script: "/bin/true"
server: 192.168.4.3
client_use_localhost: false
client_use_https: false
virt_auto_boot: true
webdir: "/var/www/cobbler"
webdir_whitelist:
  - misc
  - web
  - webui
  - localmirror
  - repo_mirror
  - distro_mirror
  - images
  - links
  - pub
  - repo_profile
  - repo_system
  - svc
  - rendered
  - .link_cache
xmlrpc_port: 25151
yum_post_install_mirror: true
yum_distro_priority: 1
yumdownloader_flags: "--resolve"
serializer_pretty_json: false
replicate_rsync_options: "-avzH"
replicate_repo_rsync_options: "-avzH"
always_write_dhcp_entries: false
proxy_url_ext: ""
proxy_url_int: ""
jinja2_includedir: "/var/lib/cobbler/jinja2"
convert_server_to_ip: false
bootloaders_dir: "/var/lib/cobbler/loaders"
buildisodir: "/var/cache/cobbler/buildiso"
cobbler_master: ""
default_virt_disk_driver: "raw"
grubconfig_dir: "/var/lib/cobbler/grub_config"
iso_template_dir: "/etc/cobbler/iso"
puppet_server: ""
puppet_version: 2
signature_path: "/var/lib/cobbler/distro_signatures.json"
signature_url: "https://cobbler.github.io/signatures/3.0.x/latest.json"
include: [ "/etc/cobbler/settings.d/*.settings" ]
